server:
  port: 8088

spring:
  application:
    name: gl-admin
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:10.30.10.49:18848}
        namespace: dev
      config:
        server-addr: ${NACOS_ADDR:10.30.10.49:18848}
        namespace: dev
        file-extension: yaml


management:
  endpoints:
    web:
      exposure:
        include: health,info
